### ISSUE TITLE
I want join this project!

### ISSUE THREAD

**Issue by momoci99** [jongfeel/BookDiscussions#1]
nang mu

**Comment by Joseph-Cha** [comment]
me too!! but.. date can be changed..? T^T..

**Comment by jongfeel** [comment]
@momoci99 
Is `nang mu` means to `no contents`? right? ㅋㅋㅋ
This meet-up already in progress and host is not me.
You can join next meet-up of new book this group, maybe Jan 2022.

But open new academic conference next year Feb!
(This group host is me.)
https://github.com/ThinkAboutSoftware/AcademicConference
Will you join this group?

**Comment by dhcha-virnect** [comment]
I will join next year conference ! 
come YeongKwon 님 ㅋㅋㅋㅋ

**Comment by momoci99** [comment]
Y.E.S
